[project]
name = 'Tokenized-Transportation-Infrastructure-Monitoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.alert-management]
path = 'contracts/alert-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.asset-registration]
path = 'contracts/asset-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.sensor-data]
path = 'contracts/sensor-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.threshold]
path = 'contracts/threshold.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
